//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CoreLib.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_INiksmsWebservice", Namespace="http://tempuri.org/")]
    public partial class NiksmsWebservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GroupSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AsyncGroupSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GroupSmsWithPatternOperationCompleted;
        
        private System.Threading.SendOrPostCallback AsyncGroupSmsWithPatternOperationCompleted;
        
        private System.Threading.SendOrPostCallback PtpSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AsyncPtpSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDiscountCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPanelExpireDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceiveSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetReceiveSmsVisitedStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSmsDeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSmsDeliveryWithClientIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServertimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSenderNumbersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NiksmsWebservice() {
            this.Url = global::CoreLib.Properties.Settings.Default.CoreLib_WebReference_NiksmsWebservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GroupSmsCompletedEventHandler GroupSmsCompleted;
        
        /// <remarks/>
        public event AsyncGroupSmsCompletedEventHandler AsyncGroupSmsCompleted;
        
        /// <remarks/>
        public event GroupSmsWithPatternCompletedEventHandler GroupSmsWithPatternCompleted;
        
        /// <remarks/>
        public event AsyncGroupSmsWithPatternCompletedEventHandler AsyncGroupSmsWithPatternCompleted;
        
        /// <remarks/>
        public event PtpSmsCompletedEventHandler PtpSmsCompleted;
        
        /// <remarks/>
        public event AsyncPtpSmsCompletedEventHandler AsyncPtpSmsCompleted;
        
        /// <remarks/>
        public event GetCreditCompletedEventHandler GetCreditCompleted;
        
        /// <remarks/>
        public event GetDiscountCreditCompletedEventHandler GetDiscountCreditCompleted;
        
        /// <remarks/>
        public event GetPanelExpireDateCompletedEventHandler GetPanelExpireDateCompleted;
        
        /// <remarks/>
        public event GetReceiveSmsCompletedEventHandler GetReceiveSmsCompleted;
        
        /// <remarks/>
        public event ResetReceiveSmsVisitedStatusCompletedEventHandler ResetReceiveSmsVisitedStatusCompleted;
        
        /// <remarks/>
        public event GetSmsDeliveryCompletedEventHandler GetSmsDeliveryCompleted;
        
        /// <remarks/>
        public event GetSmsDeliveryWithClientIdCompletedEventHandler GetSmsDeliveryWithClientIdCompleted;
        
        /// <remarks/>
        public event GetServertimeCompletedEventHandler GetServertimeCompleted;
        
        /// <remarks/>
        public event GetSenderNumbersCompletedEventHandler GetSenderNumbersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GroupSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnSmsResult GroupSms(AuthenticationModel security, GroupSmsModel model) {
            object[] results = this.Invoke("GroupSms", new object[] {
                        security,
                        model});
            return ((ReturnSmsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GroupSmsAsync(AuthenticationModel security, GroupSmsModel model) {
            this.GroupSmsAsync(security, model, null);
        }
        
        /// <remarks/>
        public void GroupSmsAsync(AuthenticationModel security, GroupSmsModel model, object userState) {
            if ((this.GroupSmsOperationCompleted == null)) {
                this.GroupSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupSmsOperationCompleted);
            }
            this.InvokeAsync("GroupSms", new object[] {
                        security,
                        model}, this.GroupSmsOperationCompleted, userState);
        }
        
        private void OnGroupSmsOperationCompleted(object arg) {
            if ((this.GroupSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupSmsCompleted(this, new GroupSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/AsyncGroupSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long AsyncGroupSms(AuthenticationModel security, GroupSmsModel model, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> callBackId, string callBackUrl) {
            object[] results = this.Invoke("AsyncGroupSms", new object[] {
                        security,
                        model,
                        callBackId,
                        callBackUrl});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void AsyncGroupSmsAsync(AuthenticationModel security, GroupSmsModel model, System.Nullable<long> callBackId, string callBackUrl) {
            this.AsyncGroupSmsAsync(security, model, callBackId, callBackUrl, null);
        }
        
        /// <remarks/>
        public void AsyncGroupSmsAsync(AuthenticationModel security, GroupSmsModel model, System.Nullable<long> callBackId, string callBackUrl, object userState) {
            if ((this.AsyncGroupSmsOperationCompleted == null)) {
                this.AsyncGroupSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAsyncGroupSmsOperationCompleted);
            }
            this.InvokeAsync("AsyncGroupSms", new object[] {
                        security,
                        model,
                        callBackId,
                        callBackUrl}, this.AsyncGroupSmsOperationCompleted, userState);
        }
        
        private void OnAsyncGroupSmsOperationCompleted(object arg) {
            if ((this.AsyncGroupSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AsyncGroupSmsCompleted(this, new AsyncGroupSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GroupSmsWithPattern", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnSmsResult GroupSmsWithPattern(AuthenticationModel security, GroupSmsWithPatternModel model) {
            object[] results = this.Invoke("GroupSmsWithPattern", new object[] {
                        security,
                        model});
            return ((ReturnSmsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GroupSmsWithPatternAsync(AuthenticationModel security, GroupSmsWithPatternModel model) {
            this.GroupSmsWithPatternAsync(security, model, null);
        }
        
        /// <remarks/>
        public void GroupSmsWithPatternAsync(AuthenticationModel security, GroupSmsWithPatternModel model, object userState) {
            if ((this.GroupSmsWithPatternOperationCompleted == null)) {
                this.GroupSmsWithPatternOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupSmsWithPatternOperationCompleted);
            }
            this.InvokeAsync("GroupSmsWithPattern", new object[] {
                        security,
                        model}, this.GroupSmsWithPatternOperationCompleted, userState);
        }
        
        private void OnGroupSmsWithPatternOperationCompleted(object arg) {
            if ((this.GroupSmsWithPatternCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupSmsWithPatternCompleted(this, new GroupSmsWithPatternCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/AsyncGroupSmsWithPattern", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long AsyncGroupSmsWithPattern(AuthenticationModel security, GroupSmsWithPatternModel model, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> callBackId, string callBackUrl) {
            object[] results = this.Invoke("AsyncGroupSmsWithPattern", new object[] {
                        security,
                        model,
                        callBackId,
                        callBackUrl});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void AsyncGroupSmsWithPatternAsync(AuthenticationModel security, GroupSmsWithPatternModel model, System.Nullable<long> callBackId, string callBackUrl) {
            this.AsyncGroupSmsWithPatternAsync(security, model, callBackId, callBackUrl, null);
        }
        
        /// <remarks/>
        public void AsyncGroupSmsWithPatternAsync(AuthenticationModel security, GroupSmsWithPatternModel model, System.Nullable<long> callBackId, string callBackUrl, object userState) {
            if ((this.AsyncGroupSmsWithPatternOperationCompleted == null)) {
                this.AsyncGroupSmsWithPatternOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAsyncGroupSmsWithPatternOperationCompleted);
            }
            this.InvokeAsync("AsyncGroupSmsWithPattern", new object[] {
                        security,
                        model,
                        callBackId,
                        callBackUrl}, this.AsyncGroupSmsWithPatternOperationCompleted, userState);
        }
        
        private void OnAsyncGroupSmsWithPatternOperationCompleted(object arg) {
            if ((this.AsyncGroupSmsWithPatternCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AsyncGroupSmsWithPatternCompleted(this, new AsyncGroupSmsWithPatternCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/PtpSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnSmsResult PtpSms(AuthenticationModel security, PtpSmsModel model) {
            object[] results = this.Invoke("PtpSms", new object[] {
                        security,
                        model});
            return ((ReturnSmsResult)(results[0]));
        }
        
        /// <remarks/>
        public void PtpSmsAsync(AuthenticationModel security, PtpSmsModel model) {
            this.PtpSmsAsync(security, model, null);
        }
        
        /// <remarks/>
        public void PtpSmsAsync(AuthenticationModel security, PtpSmsModel model, object userState) {
            if ((this.PtpSmsOperationCompleted == null)) {
                this.PtpSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPtpSmsOperationCompleted);
            }
            this.InvokeAsync("PtpSms", new object[] {
                        security,
                        model}, this.PtpSmsOperationCompleted, userState);
        }
        
        private void OnPtpSmsOperationCompleted(object arg) {
            if ((this.PtpSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PtpSmsCompleted(this, new PtpSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/AsyncPtpSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long AsyncPtpSms(AuthenticationModel security, PtpSmsModel model, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> callBackId, string callBackUrl) {
            object[] results = this.Invoke("AsyncPtpSms", new object[] {
                        security,
                        model,
                        callBackId,
                        callBackUrl});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void AsyncPtpSmsAsync(AuthenticationModel security, PtpSmsModel model, System.Nullable<long> callBackId, string callBackUrl) {
            this.AsyncPtpSmsAsync(security, model, callBackId, callBackUrl, null);
        }
        
        /// <remarks/>
        public void AsyncPtpSmsAsync(AuthenticationModel security, PtpSmsModel model, System.Nullable<long> callBackId, string callBackUrl, object userState) {
            if ((this.AsyncPtpSmsOperationCompleted == null)) {
                this.AsyncPtpSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAsyncPtpSmsOperationCompleted);
            }
            this.InvokeAsync("AsyncPtpSms", new object[] {
                        security,
                        model,
                        callBackId,
                        callBackUrl}, this.AsyncPtpSmsOperationCompleted, userState);
        }
        
        private void OnAsyncPtpSmsOperationCompleted(object arg) {
            if ((this.AsyncPtpSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AsyncPtpSmsCompleted(this, new AsyncPtpSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GetCredit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCredit(AuthenticationModel security) {
            object[] results = this.Invoke("GetCredit", new object[] {
                        security});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCreditAsync(AuthenticationModel security) {
            this.GetCreditAsync(security, null);
        }
        
        /// <remarks/>
        public void GetCreditAsync(AuthenticationModel security, object userState) {
            if ((this.GetCreditOperationCompleted == null)) {
                this.GetCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditOperationCompleted);
            }
            this.InvokeAsync("GetCredit", new object[] {
                        security}, this.GetCreditOperationCompleted, userState);
        }
        
        private void OnGetCreditOperationCompleted(object arg) {
            if ((this.GetCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreditCompleted(this, new GetCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GetDiscountCredit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetDiscountCredit(AuthenticationModel security) {
            object[] results = this.Invoke("GetDiscountCredit", new object[] {
                        security});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetDiscountCreditAsync(AuthenticationModel security) {
            this.GetDiscountCreditAsync(security, null);
        }
        
        /// <remarks/>
        public void GetDiscountCreditAsync(AuthenticationModel security, object userState) {
            if ((this.GetDiscountCreditOperationCompleted == null)) {
                this.GetDiscountCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDiscountCreditOperationCompleted);
            }
            this.InvokeAsync("GetDiscountCredit", new object[] {
                        security}, this.GetDiscountCreditOperationCompleted, userState);
        }
        
        private void OnGetDiscountCreditOperationCompleted(object arg) {
            if ((this.GetDiscountCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDiscountCreditCompleted(this, new GetDiscountCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GetPanelExpireDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> GetPanelExpireDate(AuthenticationModel security) {
            object[] results = this.Invoke("GetPanelExpireDate", new object[] {
                        security});
            return ((System.Nullable<System.DateTime>)(results[0]));
        }
        
        /// <remarks/>
        public void GetPanelExpireDateAsync(AuthenticationModel security) {
            this.GetPanelExpireDateAsync(security, null);
        }
        
        /// <remarks/>
        public void GetPanelExpireDateAsync(AuthenticationModel security, object userState) {
            if ((this.GetPanelExpireDateOperationCompleted == null)) {
                this.GetPanelExpireDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPanelExpireDateOperationCompleted);
            }
            this.InvokeAsync("GetPanelExpireDate", new object[] {
                        security}, this.GetPanelExpireDateOperationCompleted, userState);
        }
        
        private void OnGetPanelExpireDateOperationCompleted(object arg) {
            if ((this.GetPanelExpireDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPanelExpireDateCompleted(this, new GetPanelExpireDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GetReceiveSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetReceiveSmsModel[] GetReceiveSms(AuthenticationModel security, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> startDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> endDate) {
            object[] results = this.Invoke("GetReceiveSms", new object[] {
                        security,
                        startDate,
                        endDate});
            return ((GetReceiveSmsModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceiveSmsAsync(AuthenticationModel security, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            this.GetReceiveSmsAsync(security, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetReceiveSmsAsync(AuthenticationModel security, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, object userState) {
            if ((this.GetReceiveSmsOperationCompleted == null)) {
                this.GetReceiveSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceiveSmsOperationCompleted);
            }
            this.InvokeAsync("GetReceiveSms", new object[] {
                        security,
                        startDate,
                        endDate}, this.GetReceiveSmsOperationCompleted, userState);
        }
        
        private void OnGetReceiveSmsOperationCompleted(object arg) {
            if ((this.GetReceiveSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceiveSmsCompleted(this, new GetReceiveSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/ResetReceiveSmsVisitedStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ResetReceiveSmsVisitedStatus(AuthenticationModel security, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> startDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> endDate) {
            object[] results = this.Invoke("ResetReceiveSmsVisitedStatus", new object[] {
                        security,
                        startDate,
                        endDate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ResetReceiveSmsVisitedStatusAsync(AuthenticationModel security, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            this.ResetReceiveSmsVisitedStatusAsync(security, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void ResetReceiveSmsVisitedStatusAsync(AuthenticationModel security, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, object userState) {
            if ((this.ResetReceiveSmsVisitedStatusOperationCompleted == null)) {
                this.ResetReceiveSmsVisitedStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetReceiveSmsVisitedStatusOperationCompleted);
            }
            this.InvokeAsync("ResetReceiveSmsVisitedStatus", new object[] {
                        security,
                        startDate,
                        endDate}, this.ResetReceiveSmsVisitedStatusOperationCompleted, userState);
        }
        
        private void OnResetReceiveSmsVisitedStatusOperationCompleted(object arg) {
            if ((this.ResetReceiveSmsVisitedStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetReceiveSmsVisitedStatusCompleted(this, new ResetReceiveSmsVisitedStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GetSmsDelivery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SmsStatus[] GetSmsDelivery(AuthenticationModel security, long[] nikIds) {
            object[] results = this.Invoke("GetSmsDelivery", new object[] {
                        security,
                        nikIds});
            return ((SmsStatus[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSmsDeliveryAsync(AuthenticationModel security, long[] nikIds) {
            this.GetSmsDeliveryAsync(security, nikIds, null);
        }
        
        /// <remarks/>
        public void GetSmsDeliveryAsync(AuthenticationModel security, long[] nikIds, object userState) {
            if ((this.GetSmsDeliveryOperationCompleted == null)) {
                this.GetSmsDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSmsDeliveryOperationCompleted);
            }
            this.InvokeAsync("GetSmsDelivery", new object[] {
                        security,
                        nikIds}, this.GetSmsDeliveryOperationCompleted, userState);
        }
        
        private void OnGetSmsDeliveryOperationCompleted(object arg) {
            if ((this.GetSmsDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSmsDeliveryCompleted(this, new GetSmsDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GetSmsDeliveryWithClientId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetSmsDeliveryWithClientIdModel GetSmsDeliveryWithClientId(AuthenticationModel security, long yourId) {
            object[] results = this.Invoke("GetSmsDeliveryWithClientId", new object[] {
                        security,
                        yourId});
            return ((GetSmsDeliveryWithClientIdModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetSmsDeliveryWithClientIdAsync(AuthenticationModel security, long yourId) {
            this.GetSmsDeliveryWithClientIdAsync(security, yourId, null);
        }
        
        /// <remarks/>
        public void GetSmsDeliveryWithClientIdAsync(AuthenticationModel security, long yourId, object userState) {
            if ((this.GetSmsDeliveryWithClientIdOperationCompleted == null)) {
                this.GetSmsDeliveryWithClientIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSmsDeliveryWithClientIdOperationCompleted);
            }
            this.InvokeAsync("GetSmsDeliveryWithClientId", new object[] {
                        security,
                        yourId}, this.GetSmsDeliveryWithClientIdOperationCompleted, userState);
        }
        
        private void OnGetSmsDeliveryWithClientIdOperationCompleted(object arg) {
            if ((this.GetSmsDeliveryWithClientIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSmsDeliveryWithClientIdCompleted(this, new GetSmsDeliveryWithClientIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GetServertime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetServertime(AuthenticationModel security) {
            object[] results = this.Invoke("GetServertime", new object[] {
                        security});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetServertimeAsync(AuthenticationModel security) {
            this.GetServertimeAsync(security, null);
        }
        
        /// <remarks/>
        public void GetServertimeAsync(AuthenticationModel security, object userState) {
            if ((this.GetServertimeOperationCompleted == null)) {
                this.GetServertimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServertimeOperationCompleted);
            }
            this.InvokeAsync("GetServertime", new object[] {
                        security}, this.GetServertimeOperationCompleted, userState);
        }
        
        private void OnGetServertimeOperationCompleted(object arg) {
            if ((this.GetServertimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServertimeCompleted(this, new GetServertimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INiksmsWebservice/GetSenderNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetSenderNumbers(AuthenticationModel security) {
            object[] results = this.Invoke("GetSenderNumbers", new object[] {
                        security});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSenderNumbersAsync(AuthenticationModel security) {
            this.GetSenderNumbersAsync(security, null);
        }
        
        /// <remarks/>
        public void GetSenderNumbersAsync(AuthenticationModel security, object userState) {
            if ((this.GetSenderNumbersOperationCompleted == null)) {
                this.GetSenderNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSenderNumbersOperationCompleted);
            }
            this.InvokeAsync("GetSenderNumbers", new object[] {
                        security}, this.GetSenderNumbersOperationCompleted, userState);
        }
        
        private void OnGetSenderNumbersOperationCompleted(object arg) {
            if ((this.GetSenderNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSenderNumbersCompleted(this, new GetSenderNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationModel {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsDeliveryWithClientIdModel {
        
        private SmsStatus smsStatusField;
        
        private long niksmsIdField;
        
        /// <remarks/>
        public SmsStatus SmsStatus {
            get {
                return this.smsStatusField;
            }
            set {
                this.smsStatusField = value;
            }
        }
        
        /// <remarks/>
        public long NiksmsId {
            get {
                return this.niksmsIdField;
            }
            set {
                this.niksmsIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SmsStatus {
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        DoNotSend,
        
        /// <remarks/>
        InQueue,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        InsufficientCredit,
        
        /// <remarks/>
        Block,
        
        /// <remarks/>
        NotDeliverdSmsAdvertisingBlock,
        
        /// <remarks/>
        NotDeliverdBlackList,
        
        /// <remarks/>
        NotDeliverdDelay,
        
        /// <remarks/>
        NotDeliverdCanceled,
        
        /// <remarks/>
        NotDeliverdNoViber,
        
        /// <remarks/>
        NotDeliverdFiltering,
        
        /// <remarks/>
        WaitingForRecheckInOprator,
        
        /// <remarks/>
        OpratorFault,
        
        /// <remarks/>
        NotDeliveredBlocked,
        
        /// <remarks/>
        SendedButStatusNotUpdated,
        
        /// <remarks/>
        NotDeliveredDuplicate,
        
        /// <remarks/>
        NotDeliveredBlockPanel,
        
        /// <remarks/>
        NotDeliveredUnknownNumber,
        
        /// <remarks/>
        WaitingForDeliveryBeforeSend,
        
        /// <remarks/>
        NotDeliveredUnAccessible,
        
        /// <remarks/>
        NotDeliveredNotAnswered,
        
        /// <remarks/>
        NotDeliveredLineIsBusy,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReceiveSmsModel {
        
        private string messageField;
        
        private long senderNumberField;
        
        private string receiveNumberField;
        
        private int idField;
        
        private System.DateTime receiveDateField;
        
        private bool isRelayedField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public long SenderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveNumber {
            get {
                return this.receiveNumberField;
            }
            set {
                this.receiveNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRelayed {
            get {
                return this.isRelayedField;
            }
            set {
                this.isRelayedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PtpSmsModel {
        
        private string senderNumberField;
        
        private string[] numbersField;
        
        private System.DateTime sendOnField;
        
        private OperatorSmsSendType sendTypeField;
        
        private long[] yourMessageIdField;
        
        private string[] messageField;
        
        /// <remarks/>
        public string SenderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string[] Numbers {
            get {
                return this.numbersField;
            }
            set {
                this.numbersField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendOn {
            get {
                return this.sendOnField;
            }
            set {
                this.sendOnField = value;
            }
        }
        
        /// <remarks/>
        public OperatorSmsSendType SendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
            }
        }
        
        /// <remarks/>
        public long[] YourMessageId {
            get {
                return this.yourMessageIdField;
            }
            set {
                this.yourMessageIdField = value;
            }
        }
        
        /// <remarks/>
        public string[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum OperatorSmsSendType {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        AudioMessageMinute,
        
        /// <remarks/>
        AudioMessageSecod,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupSmsWithPatternModel {
        
        private string senderNumberField;
        
        private string[] numbersField;
        
        private System.DateTime sendOnField;
        
        private OperatorSmsSendType sendTypeField;
        
        private long[] yourMessageIdField;
        
        private int messagePatternIdField;
        
        /// <remarks/>
        public string SenderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string[] Numbers {
            get {
                return this.numbersField;
            }
            set {
                this.numbersField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendOn {
            get {
                return this.sendOnField;
            }
            set {
                this.sendOnField = value;
            }
        }
        
        /// <remarks/>
        public OperatorSmsSendType SendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
            }
        }
        
        /// <remarks/>
        public long[] YourMessageId {
            get {
                return this.yourMessageIdField;
            }
            set {
                this.yourMessageIdField = value;
            }
        }
        
        /// <remarks/>
        public int MessagePatternId {
            get {
                return this.messagePatternIdField;
            }
            set {
                this.messagePatternIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnSmsResult {
        
        private SmsReturn statusField;
        
        private string idField;
        
        private string warningMessageField;
        
        private long[] nikIdsField;
        
        /// <remarks/>
        public SmsReturn Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string WarningMessage {
            get {
                return this.warningMessageField;
            }
            set {
                this.warningMessageField = value;
            }
        }
        
        /// <remarks/>
        public long[] NikIds {
            get {
                return this.nikIdsField;
            }
            set {
                this.nikIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SmsReturn {
        
        /// <remarks/>
        Successful,
        
        /// <remarks/>
        UnknownError,
        
        /// <remarks/>
        InsufficientCredit,
        
        /// <remarks/>
        ForbiddenHours,
        
        /// <remarks/>
        Filtered,
        
        /// <remarks/>
        NoFilters,
        
        /// <remarks/>
        PrivateNumberIsDisable,
        
        /// <remarks/>
        ArgumentIsNullOrIncorrect,
        
        /// <remarks/>
        MessageBodyIsNullOrEmpty,
        
        /// <remarks/>
        PrivateNumberIsIncorrect,
        
        /// <remarks/>
        ReceptionNumberIsIncorrect,
        
        /// <remarks/>
        SentTypeIsIncorrect,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        PanelIsBlocked,
        
        /// <remarks/>
        SiteUpdating,
        
        /// <remarks/>
        AudioMessageNotAllowed,
        
        /// <remarks/>
        AudioMessageFileSizeNotAllowed,
        
        /// <remarks/>
        PanelExpired,
        
        /// <remarks/>
        InvalidUserNameOrPass,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupSmsModel {
        
        private string senderNumberField;
        
        private string[] numbersField;
        
        private System.DateTime sendOnField;
        
        private OperatorSmsSendType sendTypeField;
        
        private long[] yourMessageIdField;
        
        private string messageField;
        
        /// <remarks/>
        public string SenderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string[] Numbers {
            get {
                return this.numbersField;
            }
            set {
                this.numbersField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendOn {
            get {
                return this.sendOnField;
            }
            set {
                this.sendOnField = value;
            }
        }
        
        /// <remarks/>
        public OperatorSmsSendType SendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
            }
        }
        
        /// <remarks/>
        public long[] YourMessageId {
            get {
                return this.yourMessageIdField;
            }
            set {
                this.yourMessageIdField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GroupSmsCompletedEventHandler(object sender, GroupSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnSmsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnSmsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AsyncGroupSmsCompletedEventHandler(object sender, AsyncGroupSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AsyncGroupSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AsyncGroupSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GroupSmsWithPatternCompletedEventHandler(object sender, GroupSmsWithPatternCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupSmsWithPatternCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupSmsWithPatternCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnSmsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnSmsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AsyncGroupSmsWithPatternCompletedEventHandler(object sender, AsyncGroupSmsWithPatternCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AsyncGroupSmsWithPatternCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AsyncGroupSmsWithPatternCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PtpSmsCompletedEventHandler(object sender, PtpSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PtpSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PtpSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnSmsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnSmsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AsyncPtpSmsCompletedEventHandler(object sender, AsyncPtpSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AsyncPtpSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AsyncPtpSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCreditCompletedEventHandler(object sender, GetCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetDiscountCreditCompletedEventHandler(object sender, GetDiscountCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDiscountCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDiscountCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetPanelExpireDateCompletedEventHandler(object sender, GetPanelExpireDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPanelExpireDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPanelExpireDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<System.DateTime> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<System.DateTime>)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetReceiveSmsCompletedEventHandler(object sender, GetReceiveSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceiveSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceiveSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetReceiveSmsModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetReceiveSmsModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ResetReceiveSmsVisitedStatusCompletedEventHandler(object sender, ResetReceiveSmsVisitedStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetReceiveSmsVisitedStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetReceiveSmsVisitedStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetSmsDeliveryCompletedEventHandler(object sender, GetSmsDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSmsDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSmsDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SmsStatus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SmsStatus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetSmsDeliveryWithClientIdCompletedEventHandler(object sender, GetSmsDeliveryWithClientIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSmsDeliveryWithClientIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSmsDeliveryWithClientIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetSmsDeliveryWithClientIdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetSmsDeliveryWithClientIdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetServertimeCompletedEventHandler(object sender, GetServertimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServertimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServertimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetSenderNumbersCompletedEventHandler(object sender, GetSenderNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSenderNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSenderNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591