//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TfShop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ir.zarinpal.com/pg/services/WebGate/service")]
        public string TfShop_com_zarinpal_ir_PaymentGatewayImplementationService {
            get {
                return ((string)(this["TfShop_com_zarinpal_ir_PaymentGatewayImplementationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://94.182.154.28:1370/NiksmsWebservice.svc")]
        public string TfShop_NiksmsWebservice_NiksmsWebservice {
            get {
                return ((string)(this["TfShop_NiksmsWebservice_NiksmsWebservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ir.zarinpal.com/pg/services/WebGate/service")]
        public string ShopCMS_com_zarinpal_ir_PaymentGatewayImplementationService {
            get {
                return ((string)(this["ShopCMS_com_zarinpal_ir_PaymentGatewayImplementationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://94.182.154.28:1370/NiksmsWebservice.svc")]
        public string ShopCMS_NiksmsWebservice_NiksmsWebservice {
            get {
                return ((string)(this["ShopCMS_NiksmsWebservice_NiksmsWebservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bpm.shaparak.ir/pgwchannel/services/pgw")]
        public string TfShop_ir_shaparak_bpm_PaymentGatewayImplService {
            get {
                return ((string)(this["TfShop_ir_shaparak_bpm_PaymentGatewayImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sep.shaparak.ir/payments/initpayment.asmx")]
        public string TfShop_ir_shaparak_sep_PaymentIFBinding {
            get {
                return ((string)(this["TfShop_ir_shaparak_sep_PaymentIFBinding"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sep.shaparak.ir/payments/referencepayment.asmx")]
        public string TfShop_ir_shaparak_sep1_PaymentIFBinding {
            get {
                return ((string)(this["TfShop_ir_shaparak_sep1_PaymentIFBinding"]));
            }
        }
    }
}
